### ISSUE TITLE
Quick filter and site/location shortcuts

### ISSUE THREAD

**Issue by etfz** [mattieserver/netbox-topology-views#115]
Hi,

I just noticed [this comment](https://github.com/mattieserver/netbox-topology-views/issues/70#issuecomment-881490421) from a previous ticket. I'm assuming that it's from an earlier version, but I would very much like to have the filters on the same page like that. At the very least, for the site/location setting.

Sort of tying in to that, would it be possible to add some sort of link from each site/location to its topology view? It seems natural to me that it would be possible to find a site topology via the actual site.

Thanks

**Comment by thscma** [comment]
links at the navigation pane will be nice. From my point of view, it makes sense to keep this links seperate cause a topology could span multiple sites/locations

**Comment by dreng** [comment]
@etfz The image you are referring to is outdated. It shows a picture from an old version of netbox where the filter pane was positioned on the right hand side. The filter pane has since been moved to another tab. We use the UI features that netbox provides. From a user experience perspective, It would not be a good idea to do things different than netbox does. For that reason I close your proposal as "not planned".
