### ISSUE TITLE
Always save coordinates?

### ISSUE THREAD

**Issue by etfz** [mattieserver/netbox-topology-views#120]
It seems like I need to check the Save coordinates option every time I open the topology page. Not sure if there's a good reason for this (or why one wouldn't want to save it), especially considering there already exists a plugin option to enable or disable saving coordinates.

Also, mostly related, after having moved a device in the topology, it doesn't stick until I reload the page. Is this the intended behaviour?

**Comment by swgATpj** [comment]
> Also, mostly related, after having moved a device in the topology, it doesn't stick until I reload the page. Is this the intended behaviour?
That happens only on the first time. After you moved a device and reloaded the page you can move it as you want.

**Comment by mattieserver** [comment]
Hi,

I will add an extra option do always save the coordinates.

The coordinates are not enabled by default because the custom field that is needed.
In my use case, we also do not want to enable the coordinates saving by default because some people will drag the devices around to show something (and this results in unwanted changes)
