### ISSUE TITLE
Plugin will break in v3.3

### ISSUE THREAD

**Issue by jahknem** [mattieserver/netbox-topology-views#141]
Due to changes in how cables are modeled in v3.3 of Netbox terminations will have a different identifier. 
In the beta I get this error:
```
Cannot resolve keyword '_termination_a_device_id' into field. Choices are: _abs_length, color, created, custom_field_data, id, journal_entries, label, last_updated, length, length_unit, status, tagged_items, tags, tenant, tenant_id, terminations, type
```

I really like this plugin. Is it possible to adapt it to the new version?

**Comment by mattieserver** [comment]
Hi,

Yes, unfortunately the 3.3 upgrade will not work right now.
I will try to provide an update during the weekend.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jan ***@***.***>
Sent: Monday, August 8, 2022 2:56:26 PM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] Plugin will break in v3.3 (Issue #141)


Due to changes in how cables are modeled in v3.3 of Netbox terminations will have a different identifier.
In the beta I get this error:

Cannot resolve keyword '_termination_a_device_id' into field. Choices are: _abs_length, color, created, custom_field_data, id, journal_entries, label, last_updated, length, length_unit, status, tagged_items, tags, tenant, tenant_id, terminations, type


I really like this plugin. Is it possible to adapt it to the new version?

**Comment by pycolas** [comment]
Hi,
I am back from holidays and just see this new V3.3 release with all those changes on cables handling.
Do you need some help on something ?

**Comment by mattieserver** [comment]
Hi,

Thanks for the offer but I am working on the update now. (See #145)
The basics are in place but I need to finish the cercuits before making a release.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peterbaumert** [comment]
Did you remove end2end_connection stuff here or should it work now out of the box?
