### ISSUE TITLE
Show Power panel: local variable 'site_ids' referenced before assignment

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#159]
After ticking the "Show Power panel/feed" checkbox and clicking "Search" I get the following error:

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'UnboundLocalError'>

local variable 'site_ids' referenced before assignment

Python version: 3.9.2
NetBox version: 3.3.3
If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by dreng** [comment]
I just noticed that power connections are being shown if I do NOT tick the checkbox.

**Comment by mattieserver** [comment]
Hi,

It looks like i indeed made a mistake with that variable, should be fixed in next release.
As for the power outlet connections, that is maybe not so clear.

The filter option for 'power' is only for the power feeds and not the power outlets.
So cables that go to an outlet will show without that option enabled. I will change the description of the filter to make it more clear.
