### ISSUE TITLE
Improve README.md in dev_setup

### ISSUE THREAD

**Issue by dreng** [mattieserver/netbox-topology-views#185]
I followed your instructions in order to establish an environment for developing and build netbox and the plugin from scratch. Unfortunately I failed.

Please be more precise which command exactly has to be executed in which environment and directory.

First problem was that yarn hasn't been found. I had to install with "npm install --global yarn".
Second I wasn't sure why yarn gave me a "file not found". After changing to static_dev directory I got the following error:"Error: Cannot find module 'esbuild-sass-plugin'".

**Comment by mattieserver** [comment]
Hi,

Yes the docs for the dev setup are not up to date.
Yarn is no longer used, i will provide an update to the readme file.
________________________________
From: Mario ***@***.***>
Sent: Friday, November 18, 2022 2:37:51 PM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] Improve README.md in dev_setup (Issue #185)


I followed your instructions in order to establish an environment for developing and build netbox and the plugin from scratch. Unfortunately I failed.

Please be more precise which command exactly has to be executed in which environment and directory.

First problem was that yarn hasn't been found. I had to install with "npm install --global yarn".
Second I wasn't sure why yarn gave me a "file not found". After changing to static_dev directory I got the following error:"Error: Cannot find module 'esbuild-sass-plugin'".
