### ISSUE TITLE
Include icon for patch panels

### ISSUE THREAD

**Issue by candlerb** [mattieserver/netbox-topology-views#186]
It would be great if there were an included icon to represent patch panels - instead of the Roswell alien :-)

Searching at https://www.flaticon.com/free-icons/rj45 turns up [this one](https://www.flaticon.com/free-icon/lan_4828808?term=rj45&page=1&position=53&page=1&position=53&related_id=4828808&origin=tag) from Freepik, which I think would do the job.

![image](https://user-images.githubusercontent.com/44789/202927183-e6f39f47-2a96-4a1f-b118-c675c9d70aa9.png)

Perhaps also include "Patching" in preselected_device_roles and device_img?

**Comment by dreng** [comment]
I second this. The proposed icon could be misleading though. These two CAT sockets look like a network outlet. I implemented an icon in our environment that shows a few more sockets in order to make clear what it is (not).

Also, there are a few more icons that could be added. How about using this thread to collect useful infrastructure and end devices and develop an icon set that is a bit more homogeneous?

**Comment by quantum909** [comment]
maybe this one

![patch-panel-2](https://user-images.githubusercontent.com/5301445/203186818-74b17107-ca27-435b-85b0-34552e2a725e.svg)

**Comment by joaolucasmacedo** [comment]
I use this one for patch panels:

![patch-panel](https://user-images.githubusercontent.com/66760118/203312466-adc42913-9a44-46cb-b3a5-7f2b735ef61c.png)

**Comment by dreng** [comment]
Closed in favor of #240
