### ISSUE TITLE
feature request:  add rack rows

### ISSUE THREAD

**Issue by ThomasADavis** [mattieserver/netbox-topology-views#22]
I'd like to be able to draw topologies based on rack rows.

**Comment by darcynz** [comment]
And/or being able to draw by racks woulds be great in a modest DC implementation

**Comment by dreng** [comment]
@ThomasADavis NetBox does not model rack rows as far as I can see. Please correct me if I'm wrong. You should raise a feature request upstream. It's a no-brainer for us if it will be implemented. On the other hand you are able to use (sub-)locations in order to illustrate rows. A filter for locations is implemented in netbox-topology-views already. Another options would be to use tags or custom fields.

**Comment by ThomasADavis** [comment]
At the time this was requested, you couldn't filter by rack/location.

You can now, so this can be considered completed.
