### ISSUE TITLE
Open a cable trace view when double clicking a logical connection

### ISSUE THREAD

**Issue by royvegard** [mattieserver/netbox-topology-views#254]
### NetBox version

v3.4.3

### Topology Views version

v3.2.1

### Feature type

New functionality

### Proposed functionality

When double clicking on a logical connection between two nodes, the Cable Trace for Interface (`/dcim/interfaces/<interface_id>/trace/`) view should be opened. `<interfac_id>` is one of the interfaces, it does not matter which one.

### Use case

Useful for navigating to Cable Trace views.

### External dependencies

None

**Comment by dreng** [comment]
We implemented FR #181 a month ago, which allows you to open the cable details with a double click. This approach seems very logical form a user experience point of view. We would break this new feature if we'd assign a different action on double click.

That said, you can always open the cable with a double click, click on a termination port/interface and trace from there. That's two clicks more but takes not much effort and we could keep the current behavior.

**Comment by royvegard** [comment]
This will not break the double click for cables implemented in #181.  The patch changes the href of the Interface Connection edges from None to an url for the trace for the interface.

I have already made the patch, but when I opened a PR I noticed the text in the PR template to wait until status: accepted.

**Comment by dreng** [comment]
You are very welcome to contribute and I'd happily assign this to you. I have to admit that I'm not sure where this is going. Maybe I haven't understood your proposal correctly. Feel free to add a PR. We gladly gonna have a look at your work.

> I have already made the patch, but when I opened a PR I noticed the text in the PR template to wait until status: accepted.

And the current situation is exactly the reason for that. Sometimes an idea is not as good as you think at first, that happens to me too and that's why I have already closed my own FRs. Sometimes ideas are also completely out of scope. Therefore, we first want to discuss whether the proposed change is a good suggestion and whether all possible difficulties have been taken into account. Otherwise we would have a chaos product at some point.
