### ISSUE TITLE
Incorrect names displayed for power panels/feeds

### ISSUE THREAD

**Issue by nogaff** [mattieserver/netbox-topology-views#274]
### NetBox version

3.4.7

### Topology Views version

3.3.0

### Steps to Reproduce

1. Create some power panels/feeds and name them however you like.
2. Enable the "Show Power Feeds" option or filter.
3. View the topology map.

### Expected Behavior

Power panels/feeds should be displayed with the names entered in step 1.

### Observed Behavior

Power panels/feeds are displayed with generic names like "Power Panel 3" and "Power Feed 7".

**Comment by dreng** [comment]
This also applies to Circuits. It would be an easy fix. We just need to change "device.pk" into "device.name" in the following lines:

https://github.com/mattieserver/netbox-topology-views/blob/86cb967d7098d4860b02db6d9764f1296ca319b5/netbox_topology_views/views.py#L77
https://github.com/mattieserver/netbox-topology-views/blob/86cb967d7098d4860b02db6d9764f1296ca319b5/netbox_topology_views/views.py#L87

So I wonder what the intention was behind not doing it that way in the first place. @mattieserver Can you clarify this? Maybe it's an oversight, maybe it's intentional and I don't want to destroy something I probably don't fully understand. But if nothing speaks against it, I would provide a fix shortly. I also don't get the point in prefixing the names with "Circuit", "Power Panel" and "Power Feed", because the name should clearly show you what kind of device is behind it (if the name is not a completely goofy choice).

**Comment by mattieserver** [comment]
Don't think this was intentional, I think this was implemented this way because I didn't name my power feeds, but the name field was not required ( if I remember correctly).
So you can change this but might have to check if there's an actual name value.

**Comment by dreng** [comment]
This sounds strange because no matter how far back in history I go, the form fields never had the attribute "required=False". So empty names should not happen at all. I think it's safe to omit the verification. On the other hand, a verification doesn't hurt.
