### ISSUE TITLE
Add more topology view details - Interface label

### ISSUE THREAD

**Issue by tobicodesstuff** [mattieserver/netbox-topology-views#300]
### NetBox version

v3.5.1

### Topology Views version

v3.5.0

### Feature type

New functionality

### Proposed functionality

Add the possibility, for example via a checkbox 'Show interface name/label", to add the label of interfaces on the devices within the view. Currently I was unable to find any possibility of adding the interfaces of a device into view.

### Use case

Clearer picture of which interfaces are connected via which cable.

### External dependencies

None

**Comment by dreng** [comment]
Hi @tobicodesstuff,
Thank you for contributing to this plugin. As stated at https://github.com/mattieserver/netbox-topology-views/issues/253#issuecomment-1407674861, this is not possible with vis-network. Besides, this proposal does not scale. I might be useful for 1 or 2 interfaces, but imagine a switch with 50 interfaces. No one could ever read anything. So that's unlikely to be implemented.
