### ISSUE TITLE
The new Coordinate Groups feature documented in the README.md does not currently work

### ISSUE THREAD

**Issue by arcticash** [mattieserver/netbox-topology-views#333]
### NetBox version

v3.5.4

### Topology Views version

v3.5.0

### Steps to Reproduce

1. Remove cf_coordinates custom field from an existing installation, ready to migrate over to coordinate groups
2. New devices can no longer have their locations saved

### Expected Behavior

Newly created devices should be able to have their locations saved to the "default" model as documented in the readme

### Observed Behavior

Newly created devices cannot be placed, and are effected by the physics engine, falling to the bottom of the viewport.

**Comment by dreng** [comment]
Hi @arcticash,

I wonder if you are using the right version. You wrote that you are using v3.5.0 but that version hasn't got the feature implemented. You need v3.6.0-beta.1. See https://github.com/mattieserver/netbox-topology-views/releases

Unforunately we haven't got a development branch yet. This may cause confusion because the readme is up to date while the current stable release is not. I apologise for the inconvenience.

If you like to test the new feature (which would be great!), you need to check out the beta release.

**Comment by arcticash** [comment]
Ahh my mistake, that would be the issue!

I can see the v3.5.0 release is older than the readme, missed that when i was running through the docs!
