### ISSUE TITLE
Topology Views not showing new site devices

### ISSUE THREAD

**Issue by saifvs** [mattieserver/netbox-topology-views#368]
### NetBox version

3.5.9

### Topology Views version

3.6.2

### Steps to Reproduce

I had Topology View installed in netbox for about 8months now, after the recent netbox upgrade to 3.5.9 I noticed that, none of the sites that I added recently are showing up in Topology Views.

I can see the old sites though, does anyone know to fix the issue?

I was thinking of reinstalling the plugin, but wanted to know from the community.

### Expected Behavior

Topology VIew should show the devices irespective of when it was added.

### Observed Behavior

old devices and diagrams are showing but not the new devices.

**Comment by mattieserver** [comment]
Do you have any filters active?
________________________________
From: Saifudheen Sidheeq ***@***.***>
Sent: Wednesday, August 30, 2023 2:48:52 PM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] Topology Views not showing new site devices (Issue #368)


NetBox version

3.5.9

Topology Views version

3.6.2

Steps to Reproduce

I had Topology View installed in netbox for about 8months now, after the recent netbox upgrade to 3.5.9 I noticed that, none of the sites that I added recently are showing up in Topology Views.

I can see the old sites though, does anyone know to fix the issue?

I was thinking of reinstalling the plugin, but wanted to know from the community.

Expected Behavior

Topology VIew should show the devices irespective of when it was added.

Observed Behavior

old devices and diagrams are showing but not the new devices.

**Comment by saifvs** [comment]
nope, no filter added but still not showing the devices in the topology views. However when I goto the site and click on topology new devices show up, but not on the main topology view page.

**Comment by mattieserver** [comment]
If it does not contain any confidential data, can you send a screenshot of the 'tags' (like below), so i can see if its maybe a certain combination of show cables/connected/...:

![image](https://github.com/mattieserver/netbox-topology-views/assets/3049868/0bd00b45-23ed-426e-89a5-c8d37e9788eb)

**Comment by saifvs** [comment]
There is new field I noticed now, which says 'Show Unconnected', checking that option showed up the devices that are not connected. I believe this field was added as new, is it ?

Anyways, thanks for the direction, I can now see the devices.

**Comment by mattieserver** [comment]
The field was indeed added a few months ago.
