### ISSUE TITLE
Non-devices do not save coordinates

### ISSUE THREAD

**Issue by n4zmz** [mattieserver/netbox-topology-views#377]
### NetBox version

v3.4.5

### Topology Views version

v3.6.2

### Steps to Reproduce

1. Have a power panel
2. Turn on filter show power feeds
3. Move power panel icon position
4. Go back into Topology

### Expected Behavior

Any displayed ICON should save its position or be able to add a position to it.

### Observed Behavior

Power panel appears in the same location and will not save a new location.
Same for power feeds and circuit terminations

**Comment by dreng** [comment]
I just had a quick peek into the problem: Not a one-liner, I guess.

Since the device column in the coordinates model is a foreign key to the NetBox device model, it is not possible to add other things like power feeds. I think we need to add new models for each type of non-devices. I'm not sure if we can consolidate all of the models in just one view or if we have to add a view each.
