### ISSUE TITLE
Improve topology capture to vectorized images or pdf

### ISSUE THREAD

**Issue by ShadowCipher09** [mattieserver/netbox-topology-views#398]
### NetBox version

3.6

### Topology Views version

v.3.7.0

### Feature type

New functionality

### Proposed functionality

Improve the capture of the topology to vectorized images or pdf so that they do not lose quality when zooming and being able to capture large topologies

### Use case

To document very large topologies it would be great to :)

**Comment by dreng** [comment]
I'm sorry, but I have no clue what you are talking about. Please put more effort in you proposal.

What do you mean with "capture"? PNG export? In this case it is not possible to embed any vectorized images, because PNG does not support anything like this. It's a pure bitmap format. The topology itself uses SVG images and the XML export uses SVG too.

PDF export won't be implemented beacause it's by far to complex. You can instead export to XML, load that XML into draw.io and export as PDF from there.

**Comment by ShadowCipher09** [comment]
The option to take a png of the topology, if it is very extensive and is from far away is seen with a lot of zoom loses a lot of quality and pixelates, that is solved with a ".svg" or something similar, and would be very good for people who have many devices connected or many networks

**Comment by dreng** [comment]
Duplicate of #158 
You may use XML export and import the XML to draw.io, which offers many export formats.

**Comment by ShadowCipher09** [comment]
I'm gonna take a look, thanks!
