### ISSUE TITLE
Topology not showing up

### ISSUE THREAD

**Issue by joaolucasmacedo** [mattieserver/netbox-topology-views#407]
### NetBox version

v3.6.4

### Topology Views version

v3.8.0

### Steps to Reproduce

Fresh install the plugin.
Topology only shows on sites page.
Also if I select the option "Draw Default Layout" it show the topology with all devices on NetBox, but if I tweak anything on filters I get nothing.

Python 3.10.12
Ubuntu 22.04.

### Expected Behavior

Show network topology.

### Observed Behavior

No icons are shown.

**Comment by islepnev** [comment]
Select Topology views -> Filters, Section Options.
Checkbox "Show Unconnected" is checked (along with some other Show options).
Location id 60 is selected.
I have noticed that some URI parameters are missing after upgrade.

Expected behavior: URI looks like https://netbox.example.com/plugins/netbox_topology_views/topology/?location_id=60&show_unconnected=on&show_cables=on&show_logical_connections=on&show_single_cable_logical_conns=on&draw_init=false
Actual behavior: URI is https://netbox.example.com/plugins/netbox_topology_views/topology/?location_id=60

Netbox 3.6.4
Plugin 3.8.0

**Comment by joaolucasmacedo** [comment]
Looks like it is something related to filters and the URI.
I used a custom link to open the topology with some options on a given site and it works.

**Comment by kkthxbye-code** [comment]
Can confirm that this is an issue in netbox 3.6.4 (only this version).

It broke because of this PR: https://github.com/netbox-community/netbox/pull/13963

The reason the checkboxes are removed is because of this code:

https://github.com/netbox-community/netbox/blob/5b2f29480a42e9c815ca1f50403c115cc89b6538/netbox/project-static/src/netbox.ts#L42-L52

The purpose of that code is to remove blank GET parameters for GET requests. For some reason the filter form doesn't parse properly with FormData, so the unset boolean fields do not show up. If we remove the hidden input with the duplicate name in the form that Jeremy added:

https://github.com/netbox-community/netbox/pull/13963/files#diff-a7a7e86d33a64b8b4ad7c22127a3b6f826cad0e7ca22c6cf6c61c647a8701034R5

Then it works. I verified that this is also the case for netbox core, however netbox core does not use any BooleanFields in any GET forms, instead using NullBooleanField which is a select widget.

Not sure what the right solution here is. The netbox PR is very hackish imo, but I think it's unlikely that an issue will be accepted for this, so you might have to workaround it somehow.

**Comment by rlljorge** [comment]
The same problem here, in net box v3.6.3 works.

**Comment by joaolucasmacedo** [comment]
> The same problem here, in net box v3.6.3 works.

I also have other NetBox v3.6.3 that works fine.

**Comment by joaolucasmacedo** [comment]
> Can confirm that this is an issue in netbox 3.6.4 (only this version).
> 
> It broke because of this PR: [netbox-community/netbox#13963](https://github.com/netbox-community/netbox/pull/13963)
> 
> The reason the checkboxes are removed is because of this code:
> 
> https://github.com/netbox-community/netbox/blob/5b2f29480a42e9c815ca1f50403c115cc89b6538/netbox/project-static/src/netbox.ts#L42-L52
> 
> The purpose of that code is to remove blank GET parameters for GET requests. For some reason the filter form doesn't parse properly with FormData, so the unset boolean fields do not show up. If we remove the hidden input with the duplicate name in the form that Jeremy added:
> 
> https://github.com/netbox-community/netbox/pull/13963/files#diff-a7a7e86d33a64b8b4ad7c22127a3b6f826cad0e7ca22c6cf6c61c647a8701034R5
> 
> Then it works. I verified that this is also the case for netbox core, however netbox core does not use any BooleanFields in any GET forms, instead using NullBooleanField which is a select widget.
> 
> Not sure what the right solution here is. The netbox PR is very hackish imo, but I think it's unlikely that an issue will be accepted for this, so you might have to workaround it somehow.

Thank! I hope it is possible to be fixed on next NetBox release or the next topology-views release.
