### ISSUE TITLE
Feature request: Custom Background

### ISSUE THREAD

**Issue by NetworkSeb** [mattieserver/netbox-topology-views#425]
### NetBox version

v3.6.4

### Topology Views version

v3.8.1

### Feature type

New functionality

### Proposed functionality

The ability to specify a custom background for the topology to be displayed on

### Use case

This would be beneficial when overlaying the topology on a map

### External dependencies

Unsure!

**Comment by mattieserver** [comment]
Hi,

This has been requested a few times but it would not work due to scaling/zooming in.

I was going to make a new plugin to implement this but I don't have the motivation to do it anymore.

It looks like the plugin 'netbox-plugin-device-map' does what you want.
________________________________
From: Seb Harrington ***@***.***>
Sent: Tuesday, November 14, 2023 1:53:36 PM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] Feature request: Custom Background (Issue #425)


NetBox version

v3.6.4

Topology Views version

v3.8.1

Feature type

New functionality

Proposed functionality

The ability to specify a custom background for the topology to be displayed on

Use case

This would be beneficial when overlaying the topology on a map

External dependencies

Unsure!
