### ISSUE TITLE
Must "touch" devices in topology-view before exporting XML, or else all devices will be overlapping.

### ISSUE THREAD

**Issue by sliddjur** [mattieserver/netbox-topology-views#433]
### NetBox version

v3.6.7

### Topology Views version

v3.8.1

### Steps to Reproduce

- Click plugin and then topology views
- filter for a site
- click connected devices

In topology views, everything looks good, and devices are not overlapping
- click export XML button
- import to drawio

Now all devices are overlapping

### Expected Behavior

I expect all devices being in the correct "position" in xml drawio output.
How it looks in topology views.
![image](https://github.com/mattieserver/netbox-topology-views/assets/10002057/9eb13847-6c92-4a98-841c-6c213ad96d67)

### Observed Behavior

About 10 devices that has not been touched in topology-view plugin before export.
![image](https://github.com/mattieserver/netbox-topology-views/assets/10002057/0816547e-65af-4107-8828-e8d79052908b)

**Comment by dreng** [comment]
Since you didn't touch the problematic devices, there's no information about their position in the database. Therefore, the export mechanism hasn't got any information either which results in placing all these icons to a default position.

The positions you see in your first picture are being generated automatically and dynamically by the (third party) physics engine we use (vis.network). The physics engine always jumps in when there's no information about the desired position. Unfortunately draw.io hasn't got such a physics engine, so we have to guess where to place them.

You can work around this by selecting all problematic icons and drag them >= 1 pixel away from their original position. The position information will be stored in the database then.

That said, I will have a look at it and see if there's any information about the current position of icons that were placed by the physics engine.

**Comment by dreng** [comment]
> That said, I will have a look at it and see if there's any information about the current position of icons that were placed by the physics engine.

Sorry to say that unfortunately there seems to be no way to get the current position of a physics-controlled node. We have to leave it as it is.
