### ISSUE TITLE
Show device information

### ISSUE THREAD

**Issue by deanfourie1** [mattieserver/netbox-topology-views#484]
### NetBox version

v3.7.4

### Topology Views version

3.9.1

### Feature type

New functionality

### Proposed functionality

The ability to show the IP address underneath the labels on the map

### Use case

ability to easily obtain the IP addresses of devices, and also find free ip addresses.

**Comment by dreng** [comment]
Hi,

NTV displays devices, not Interfaces or IP addresses. We've had some proposals like this before. The problem is that IP addresses (or MAC addresses) don't belong to devices. So, technically speaking, there are no "IP addresses of devices". There are IP addresses of interfaces.

A device can easily have 50 interfaces. Interfaces can have theoretically an unlimited number of IP addresses. NetBox models this situation exactly like it is in the real world.

Imagine a router or L3 switch with a bunch of IP addresses for interfaces and virtual interfaces (for vlans). Which IP address are we supposed to display? Displaying all of them would end in a complete chaos.

**Comment by Azmodeszer** [comment]
NetBox allows the assignment of a single primary IPv4 and/or IPv6 directly to a device, though (and a single OOB IP). Having a toggle for that/those might be handy.

**Comment by dreng** [comment]
> NetBox allows the assignment of a single primary IPv4 and/or IPv6 directly to a device, though (and a single OOB IP).

You are right. These ones are indeed device propoerties. I havn't had that in mind.

> Having a toggle for that/those might be handy.

Why not offer three checkboxes or a multiple choice combobox to allow any combination?

We could possibly extend this to all possible device properties, both in the label and in the popup. That way, every user can set what is important to them.
Unfortunately, you can only format the labels as a whole and not individual parts. However, line breaks are possible. The popup is HTML, so anything goes.

**Comment by deanfourie1** [comment]
So you think we can expect this in an upcoming update.

Would be nice if I could print out a diagram like this, which included the ip addresses for reference :)

**Comment by deanfourie1** [comment]
Any movement on this? This would be a great feature

**Comment by dreng** [comment]
> Any movement on this? This would be a great feature

Yes. If you read carefully, you will see that there's already a PR. We have to wait until @mattieserver approves this PR and releases a new version.

**Comment by deanfourie1** [comment]
> > Any movement on this? This would be a great feature
> 
> Yes. If you read carefully, you will see that there's already a PR. We have to wait until @mattieserver approves this PR and releases a new version.

Ok thank you very much!
