### ISSUE TITLE
Feature request: Include virtualization devices in topology map

### ISSUE THREAD

**Issue by petersipos** [mattieserver/netbox-topology-views#51]
Hello!

That is possible to show virtualized devices in the topology map? In netbox we could assign the same device roles (firewall, access switch, virtual server, server) to the virtual machines like the phisical devices, but they aren't included in the topology map yet.

Thanks,
Peter

**Comment by sscotter** [comment]
I too would really benefit from this feature. Cheers! 🍻

**Comment by tacerus** [comment]
I'd be really interested in this as well!

**Comment by focheur91300** [comment]
I'd be really interested in this as well!

**Comment by dreng** [comment]
Please put more effort in your proposal. How exactly would you like to be this feature implemented? It may help to provide mockups either.

The problem here is, that we display physical connections. In your case, the current implementation shows cables between the virtualisation host to e.g. a physical switch. What would you suggest about how the VMs, virtual connections and virtual switches should be represented without confusion with physical connections?

**Comment by dreng** [comment]
After reading and tinkering a bit I sadly have to say that the implementation of this feature is not possible. The reason is NetBox itself, because virtual cables and connections between virtual devices are not implemented right now and there are currently no plans to do so. See https://github.com/netbox-community/netbox/issues/2797

We are not able to display any connections if they don't exist in NetBox. Therefore I close this FR.

**Comment by desrod** [comment]
Displaying connected/hosted VMs would also be a nice addition, while you're in here. Currently, there's no way to make VMs visible, regardless of their role. You only see "baremetal" devices. It's missing a pretty significant gap for netbox, given that _everything_ is moving to containers and VMs these days.

**Comment by dreng** [comment]
@desrod Did you read my last comment? If you like to have such a feature, please make a feature request upstream and convince the netbox team in modeling VM networking. Without that, displaying just VM icons in a topology map is completely useless. Besides, please open a new feature request if you'd like to make one. Don't hijack closed FRs for new FRs.

**Comment by divulgacheur** [comment]
Hello @dreng,

I think you are mistaken: displaying "just VM icons" in a topology map is not useless, as this topology can be exported to draw.io for exemple and edited by hand until NetBox supports VM networking.

For a hosting company using NetBox as a CMDB, it is crucial to include virtual machines in the topology map since modern IT environments increasingly rely on virtualization and containers. This provides a comprehensive and accurate view of their infrastructure and their clients' infrastructure.

If connections are mandatory, why does the "Show Unconnected" option exist in this plugin?
