### ISSUE TITLE
Topology view Configures the permissions for this function

### ISSUE THREAD

**Issue by yjoke** [mattieserver/netbox-topology-views#579]
### NetBox version

v4.1.3

### Topology Views version

v4.1.0

### Feature type

New functionality

### Proposed functionality

Why can't I control the two parts "Topology->Topology" and "Topology->Images" in the permission configuration? I can't find these two lines in the permission list. Is that by design? Why not manage these permissions.

### Use case

Some users don't have permission to see the line links, but I have no way to reclaim permission for the topology view.

**Comment by dreng** [comment]
Hi,

"Topology->Images" is called "Topology->Role Image". because the model has been named like that. The Topology menu entry itself doesn't have an own model. It just refers to the device model. In fact, the topology is just a graphical view of devices (instead of a list).

Please refer to the [docs](https://github.com/netbox-community/netbox-topology-views#permissions). The needed permissions for the menu entry should be DCIM > Site: View and DCIM > Device: View.
