### ISSUE TITLE
Show neighbors option

### ISSUE THREAD

**Issue by darcynz** [mattieserver/netbox-topology-views#64]
Quite often when we look at a device, we know the device we want to visualize but not what it connects to. When you look at cables for a specific device you can see the neighbor.. 

Not sure if it would be possible, but a check box that allows the user to hide or show neighbors of the device(s) filtered could be quite useful.

**Comment by dreng** [comment]
This idea is two years old now and I think that we should take care of it. While your proposal seems to be a quite handy feature, we need to put some more effort into what is wanted here.

1. When you talk about neighbors, do you  mean the connection (far-end termination) or the link peer (device next to origin)? While a connection may be a logical connection, the link peer is always connected directly with a physical cable. This means that a neighbor might be a network socket that is mounted on a wall.
2. Do you want to show all neighbors based on the fitered result set or do you propose to show neighbors of explicitly filtered devices? Assume your filtered result set includes 5 switches and 5 patch panels, 24 ports each. Instead of receiving 10 devices you would receive up to 250 devices. While this might be exactly what you want, it may lead to a huge amount of devices when using loose filter settings. It might be a better solution to include only explicitly choosen devices for finding neighbors. However, that may not be an intuitive user experience.

**Comment by dreng** [comment]
As it is not sure if the original poster is still interested in this feature, I decided to answer the open questions to myself and take work on it. The following will be implemented:

- New filter option "Show Neighbors"
- Corresponding individual option
- Considered port types: interfaces, front ports, rear ports
- Neighbors will be automatically added based on the filter result set
- Directly connected neighbors (link peers) will be added if "Show Cables" has been ticked
- Connections (far-end terminations) will be added if "Show Logica Connections" has been ticked
- If "Show Neighbors" is ticked but neither "Show Cables" nor "Show Logical Connections", nothing will be displayed at all. This correspondes to the current behavior.
