### ISSUE TITLE
VLANs in Topoplogy

### ISSUE THREAD

**Issue by Narek307** [mattieserver/netbox-topology-views#71]
First of all thank you for this great plugin.
I would like to if there is way to show VLANs in topology?

**Comment by dreng** [comment]
To the thread opener and all that reacted with a thumbs up: I wonder how you would visualise that. Let's say, we've got a 48-port switch with a hundred tagged and untagged VLANs spread all over the ports. How could this look like?

Like this?
![vlans](https://user-images.githubusercontent.com/20901110/211144604-215af89b-f9da-4ac2-9498-1a608b25b779.png)
Or like that?
![vlans2](https://user-images.githubusercontent.com/20901110/211144816-45f531e0-57fa-4071-bfaa-74bb76670cd8.png)

And that's just a small part of all ports and VLANs.

I can only image to somehow integrate the information into the mouseover popup text. But visualising all VLANs seems to be impossible to me.

I'm looking forward to your suggestions.

**Comment by RataDP** [comment]
As our internal documentation we will like the second option you showed, the tag in the cables. But this is a mess when you have a lot of cables.


This is an example of our diagrams, but if you think with more cables, this is unmanageable.
![image](https://user-images.githubusercontent.com/3502137/211567518-df352423-bc3b-4371-abf6-55e515ab7cb6.png)


The best approach will be to put the information in the popup, something like:

```
Cable between
SwitchCore1 [Gi01]
SwitchAccess55 [Gi24]
VLANs: 5U, 11-18T, 20T
```

**Comment by dreng** [comment]
> As our internal documentation we will like the second option you showed, the tag in the cables. 

The intention of these pictures was to show that it is not a good idea at all.

> This is an example of our diagrams, but if you think with more cables, this is unmanageable.

Correct. That doesn't scale at all.
 
> The best approach will be to put the information in the popup, something like:

I don't agree, because this doesn't scale either. You've got a maximum of 4 VLANs in your example, which is not even close to the real world. Besides, a VLAN is never bound to a cable, but to an interface. I think it's a very bad idea to display it differently. No one could tell if the VLANs belong to termination A, B or both. If you remove the cable, there are no VLANs anymore. That's against NetBox' philosophy of reflecting the real world.
