### ISSUE TITLE
Move preferences from config file to GUI

### ISSUE THREAD

**Issue by nikor30** [mattieserver/netbox-topology-views#78]
Just for other users would be great to have the configuration moving from config file into the gui.

Also having there better possibility to connect icons with device types

Also having maybe there the possibility to upload custom icons 

Regards and thanks for this great plugin

**Comment by dreng** [comment]
You addressed 3 feature requests in your proposal. You should open a proposal for each FR instead. Otherwise it's difficult to handle and we may overlook something.

- Customizable Icons have been addressed in PR #193 . 
- Icon upload has to go in another FR
- Move config to GUI / database is what I'm going to start working on

I'm planning to implement two config sections:

1. Individual config preferences that are bound to a user. This includes individually predefined states of the checkboxes like 'Show Cables' or 'Show Wireless Links'. Every user only sees his own preferences then. They are automatically applied at the filter tab by querying the database.
2. Admin preferences where you are able to override default values just like you do in the config file now. This includes e.g. 'preselected_device_roles' or 'static_image_directory'.
In order to keep backwards compatibility we may define priorities (e.g. config file highest, GUI config lowest). On the other hand it's not a big deal to reapply the config settings in the GUI.

I'm also planning to rename those checkboxes that are named like 'Hide ...' into 'Show ...' in order to have a consistent logic. This was already addressed in #238 .
